package it.vige.nam.stub;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(
    name = "SignIntegrationBigService",
    wsdlLocation = "classpath:wsdl/SignIntegrationBigServices.wsdl",
    targetNamespace = "http://service.ws.nam/")
/**
 * This class was generated by Apache CXF 3.1.11 2017-04-20T12:22:20.231+02:00 Generated source
 * version: 3.1.11
 */
public class SignIntegrationBigService extends Service {

  /** The wsd location. */
  public static final URL WSDL_LOCATION;

  public static final QName SERVICE =
      new QName("http://service.ws.nam/", "SignIntegrationBigService");
  public static final QName SignIntegrationBigPort =
      new QName("http://service.ws.nam/", "SignIntegrationBigPort");

  static {
    URL url = null;
    url =
        SignIntegrationBigService.class
            .getClassLoader()
            .getResource("wsdl/SignIntegrationBigServices.wsdl");
    if (url == null) {
      java.util.logging.Logger.getLogger(SignIntegrationBigService.class.getName())
          .log(
              java.util.logging.Level.INFO,
              "Can not initialize the default wsdl from {0}",
              "classpath:wsdl/SignIntegrationBigServices.wsdl");
    }
    WSDL_LOCATION = url;
  }

  /**
   * Constructs a new SignIntegrationBigService instance.
   *
   * @param wsdlLocation the wsdlLocation
   */
  public SignIntegrationBigService(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  /**
   * Constructs a new SignIntegrationBigService instance.
   *
   * @param wsdlLocation the wsdlLocation
   * @param serviceName the serviceName
   */
  public SignIntegrationBigService(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  /** Constructs a new SignIntegrationBigService instance. */
  public SignIntegrationBigService() {
    super(WSDL_LOCATION, SERVICE);
  }

  /** Constructs a new SignIntegrationBigService instance. */
  public SignIntegrationBigService(WebServiceFeature... features) {
    super(WSDL_LOCATION, SERVICE);
  }

  /**
   * Constructs a new SignIntegrationBigService instance.
   *
   * @param wsdlLocation the wsdlLocation
   */
  public SignIntegrationBigService(URL wsdlLocation, WebServiceFeature... features) {
    super(wsdlLocation, SERVICE);
  }

  /**
   * Constructs a new SignIntegrationBigService instance.
   *
   * @param wsdlLocation the wsdlLocation
   * @param serviceName the serviceName
   */
  public SignIntegrationBigService(
      URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name = "SignIntegrationBigPort")
  /**
   * @return returns SignIntegrationBig
   */
  public SignIntegrationBig getSignIntegrationBigPort() {
    return super.getPort(SignIntegrationBigPort, SignIntegrationBig.class);
  }

  @WebEndpoint(name = "SignIntegrationBigPort")
  /**
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *     Supported features not in the <code>features</code> parameter will have their default
   *     values.
   * @return returns SignIntegrationBig
   */
  public SignIntegrationBig getSignIntegrationBigPort(WebServiceFeature... features) {
    return super.getPort(SignIntegrationBigPort, SignIntegrationBig.class, features);
  }
}
