package it.vige.nam.stub;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "SignIntegrationService", wsdlLocation = "classpath:wsdl/SignIntegrationService.wsdl", targetNamespace = "http://service.ws.nam/")
/**
* This class was generated by Apache CXF 3.1.11 2017-04-20T12:22:19.914+02:00
* Generated source version: 3.1.11
*
 */
public class SignIntegrationService extends Service {

/**
* The wsd location.
 */
	public final static URL WSDL_LOCATION;

	public final static QName SERVICE = new QName("http://service.ws.nam/", "SignIntegrationService");
	public final static QName SignIntegrationPort = new QName("http://service.ws.nam/", "SignIntegrationPort");
	static {
		URL url = null;
		url = SignIntegrationService.class.getClassLoader().getResource("wsdl/SignIntegrationService.wsdl");
		if (url == null) {
			java.util.logging.Logger.getLogger(SignIntegrationService.class.getName()).log(java.util.logging.Level.INFO,
					"Can not initialize the default wsdl from {0}", "classpath:wsdl/SignIntegrationService.wsdl");
		}
		WSDL_LOCATION = url;
	}

/**
* Constructs a new SignIntegrationService instance.
* @param wsdlLocation the wsdlLocation
 */
	public SignIntegrationService(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

/**
* Constructs a new SignIntegrationService instance.
* @param wsdlLocation the wsdlLocation
* @param serviceName the serviceName
 */
	public SignIntegrationService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

/**
* Constructs a new SignIntegrationService instance.
 */
	public SignIntegrationService() {
		super(WSDL_LOCATION, SERVICE);
	}

/**
* Constructs a new SignIntegrationService instance.
 */
	public SignIntegrationService(WebServiceFeature... features) {
		super(WSDL_LOCATION, SERVICE);
	}

/**
* Constructs a new SignIntegrationService instance.
* @param wsdlLocation the wsdlLocation
 */
	public SignIntegrationService(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, SERVICE);
	}

/**
* Constructs a new SignIntegrationService instance.
* @param wsdlLocation the wsdlLocation
* @param serviceName the serviceName
 */
	public SignIntegrationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName);
	}

	@WebEndpoint(name = "SignIntegrationPort")
/**
*
* @return returns SignIntegration
 */
	public SignIntegration getSignIntegrationPort() {
		return super.getPort(SignIntegrationPort, SignIntegration.class);
	}

	@WebEndpoint(name = "SignIntegrationPort")
/**
*
* @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure
*                 on the proxy. Supported features not in the
*                 <code>features</code> parameter will have their default
*                 values.
* @return returns SignIntegration
 */
	public SignIntegration getSignIntegrationPort(WebServiceFeature... features) {
		return super.getPort(SignIntegrationPort, SignIntegration.class, features);
	}

}
