package it.vige.nam.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11 2017-04-20T12:22:20.223+02:00
 * Generated source version: 3.1.11
 *
 */
@WebService(targetNamespace = "http://service.ws.nam/", name = "SignIntegrationBig")
@XmlSeeAlso({ ObjectFactory.class })
public interface SignIntegrationBig {

	@WebMethod
	@RequestWrapper(localName = "signCAdESByAttachment", targetNamespace = "http://service.ws.nam/", className = "it.vige.nam.stub.SignCAdESByAttachment")
	@ResponseWrapper(localName = "signCAdESByAttachmentResponse", targetNamespace = "http://service.ws.nam/", className = "it.vige.nam.stub.SignCAdESByAttachmentResponse")
	@WebResult(name = "return", targetNamespace = "")
	public javax.activation.DataHandler signCAdESByAttachment(
			@WebParam(name = "credentials", targetNamespace = "") it.vige.nam.stub.Credentials credentials,
			@WebParam(name = "inputDataHandler", targetNamespace = "") javax.activation.DataHandler inputDataHandler,
			@WebParam(name = "CAdESPreferences", targetNamespace = "") it.vige.nam.stub.CAdESPreferences cAdESPreferences)
			throws WSException;

	@WebMethod
	@RequestWrapper(localName = "verifyCAdESByAttachment", targetNamespace = "http://service.ws.nam/", className = "it.vige.nam.stub.VerifyCAdESByAttachment")
	@ResponseWrapper(localName = "verifyCAdESByAttachmentResponse", targetNamespace = "http://service.ws.nam/", className = "it.vige.nam.stub.VerifyCAdESByAttachmentResponse")
	@WebResult(name = "return", targetNamespace = "")
	public it.vige.nam.stub.SignedDocumentReportBean verifyCAdESByAttachment(
			@WebParam(name = "inputDataHandler", targetNamespace = "") javax.activation.DataHandler inputDataHandler,
			@WebParam(name = "preferences", targetNamespace = "") it.vige.nam.stub.VerifyPreferences preferences)
			throws WSException;
}
