
package it.vige.nam.stub;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 3.1.11 2017-04-20T12:22:20.211+02:00
 * Generated source version: 3.1.11
 */

@WebFault(name = "WSException", targetNamespace = "http://service.ws.nam/")
/**
 * Class providing functionality for Alfresco testing.
 * 
 * @author vige
 */
public class WSException extends Exception {

	private it.vige.nam.stub.WsFaultBean wsException;

 /**
 * Constructs a new w s exception.
 *
 * @return the result
 */
	public WSException() {
		super();
	}

 /**
 * Constructs a new w s exception.
 *
 * @param message the message
 * @return the result
 */
	public WSException(String message) {
		super(message);
	}

 /**
 * Constructs a new w s exception.
 *
 * @param message the message
 * @param cause the cause
 * @return the result
 */
	public WSException(String message, Throwable cause) {
		super(message, cause);
	}

 /**
 * Constructs a new w s exception.
 *
 * @param message the message
 * @param wsException the ws exception
 * @return the result
 */
	public WSException(String message, it.vige.nam.stub.WsFaultBean wsException) {
		super(message);
		this.wsException = wsException;
	}

 /**
 * Constructs a new w s exception.
 *
 * @param message the message
 * @param wsException the ws exception
 * @param cause the cause
 * @return the result
 */
	public WSException(String message, it.vige.nam.stub.WsFaultBean wsException, Throwable cause) {
		super(message, cause);
		this.wsException = wsException;
	}

 /**
 * Get fault info.
 *
 * @return the it.vige.nam.stub. ws fault bean
 */
	public it.vige.nam.stub.WsFaultBean getFaultInfo() {
		return this.wsException;
	}
}
