
package it.vige.nam.stub;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 3.1.11 2017-04-20T12:22:20.211+02:00
 * Generated source version: 3.1.11
 */

@WebFault(name = "WSException", targetNamespace = "http://service.ws.nam/")
public class WSException extends Exception {

	private it.vige.nam.stub.WsFaultBean wsException;

	public WSException() {
		super();
	}

	public WSException(String message) {
		super(message);
	}

	public WSException(String message, Throwable cause) {
		super(message, cause);
	}

	public WSException(String message, it.vige.nam.stub.WsFaultBean wsException) {
		super(message);
		this.wsException = wsException;
	}

	public WSException(String message, it.vige.nam.stub.WsFaultBean wsException, Throwable cause) {
		super(message, cause);
		this.wsException = wsException;
	}

	public it.vige.nam.stub.WsFaultBean getFaultInfo() {
		return this.wsException;
	}
}
