package it.vige.ws.test;

import static org.springframework.extensions.webscripts.Status.STATUS_OK;
import static org.apache.log4j.Logger.getLogger;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.Serializable;
import java.text.ParseException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.alfresco.mock.test.ws.AbstractWSForm;
import org.alfresco.mock.test.ws.MockWebScriptRequest;
import org.alfresco.mock.test.ws.MockWebScriptResponse;
import org.alfresco.model.ContentModel;
import org.alfresco.service.cmr.repository.NodeRef;
import org.alfresco.service.cmr.repository.NodeService;
import org.alfresco.service.cmr.repository.StoreRef;
import org.alfresco.service.cmr.search.SearchService;
import org.alfresco.service.namespace.QName;
import org.apache.commons.io.FileUtils;
import org.apache.log4j.Logger;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.extensions.webscripts.AbstractWebScript;
import org.springframework.extensions.webscripts.WebScriptRequest;

import com.google.common.io.ByteStreams;

import it.vige.ws.api.SignPDFGeneration;
import it.vige.ws.dom.VigeWSContentModel;

/**
 * Test class for the SignPDFGeneration WebScript.
 * Tests the generation and signing of PDF documents.
 *
 * @author lucastancapiano
 */
public class SignPDFGenerationTest extends AbstractWSForm {

	/** The logger instance. */
	private final static Logger logger = getLogger(SignPDFGenerationTest.class);

	/** The test partner ID. */
	private final static String ID_PARTNER = "prova";

	/** The test practice ID. */
	private final static String ID_PRATICA = "prova";

	/** The test DRL rule name. */
	private final static String DRL_NAME = "rf_006";

	/** The test practice month. */
	private final static String MESE_PRATICA = "01";

	/** The test practice year. */
	private final static String ANNO_PRATICA = "1980";

	/** The test document ID. */
	private final static String ID_DOC = "idddddd";

	/** The expected result folder path. */
	private final static String FOLDER_RISULTATO = "/sites/vige-site/documentLibrary/Questions/" + ID_PARTNER + "/"
			+ ANNO_PRATICA + "/" + MESE_PRATICA + "/" + ID_PRATICA + "/Autogenerated/" + DRL_NAME + ".pdf";

	/** The template variables map. */
	private Map<String, String> templateVars;

	/** The SignPDFGeneration WebScript. */
	@Autowired
	private SignPDFGeneration signPDFGeneration;

	/** The node service. */
	@Autowired
	private NodeService nodeService;

	/**
	 * Gets the abstract webscript under test.
	 *
	 * @return the SignPDFGeneration webscript
	 */
	@Override
	protected AbstractWebScript getAbstractWebScript() {
		return signPDFGeneration;
	}

	/**
	 * Initializes the test environment.
	 * Creates required folders, sites, and test documents.
	 */
	@Before
	public void init() {
		super.init();
		templateVars = new HashMap<String, String>();
		templateVars.put("idpartner", ID_PARTNER);
		templateVars.put("idpratica", ID_PRATICA);
		templateVars.put("annopratica", ANNO_PRATICA);
		templateVars.put("mesepratica", MESE_PRATICA);

		// Creating initial folders and sites
		NodeRef bdm = insertFolder(sites, "vige-site");
		NodeRef bdmDL = insertFolder(bdm, "documentLibrary");
		insertFolder(bdmDL, "Questions");
		NodeRef sys = insertFolder(bdmDL, "sys");
		NodeRef rules = insertFolder(sys, "Rules");
		NodeRef template = insertFolder(sys, "Template");
		NodeRef generic = insertFolder(template, "Generic");

		Map<QName, Serializable> properties = new HashMap<QName, Serializable>();
		properties.put(ContentModel.PROP_NAME, DRL_NAME + ".drl");
		InputStream content = this.getClass().getClassLoader().getResourceAsStream("rules/" + DRL_NAME + ".drl");
		try {
			insertDocument(rules, DRL_NAME + ".drl", ByteStreams.toByteArray(content), properties);
		} catch (Exception ex) {
			logger.error(ex);
		}
		properties = new HashMap<QName, Serializable>();
		properties.put(ContentModel.PROP_NAME, DRL_NAME + ".docx");
		try {
			File file = new File("src/test/resources/docs/" + DRL_NAME + ".docx");
			content = FileUtils.openInputStream(file);
			insertDocument(generic, DRL_NAME + ".docx", ByteStreams.toByteArray(content), properties);
		} catch (Exception ex) {
			logger.error(ex);
		}
	}

	/**
	 * Tests the execution of SignPDFGeneration webscript.
	 * Verifies that the PDF document is generated with correct aspects and properties.
	 *
	 * @throws ParseException if date parsing fails
	 * @throws IOException if an I/O error occurs
	 */
	@Test
	public void execute() throws ParseException, IOException {

		logger.debug("start test");
		SearchService searchService = serviceRegistry.getSearchService();
		InputStream jsonStream = this.getClass().getClassLoader().getResourceAsStream("json_lecters.json");
		String json = new String(ByteStreams.toByteArray(jsonStream));
		Map<String, Serializable> fields = new HashMap<String, Serializable>();
		{
			fields.put("prova", json);
		}
		WebScriptRequest webScriptRequest = new MockWebScriptRequest("json", templateVars, signPDFGeneration, fields,
				serviceRegistry);
		MockWebScriptResponse webScriptResponse = new MockWebScriptResponse();
		signPDFGeneration.execute(webScriptRequest, webScriptResponse);

		// Verify
		List<NodeRef> nodeRefs = searchService
				.query(StoreRef.STORE_REF_WORKSPACE_SPACESSTORE, SearchService.LANGUAGE_XPATH, FOLDER_RISULTATO)
				.getNodeRefs();
		NodeRef result = nodeRefs.get(0);
		Assert.assertNotNull("Folder created", result);
		Set<QName> aspects = nodeService.getAspects(result);
		for (QName aspect : aspects) {
			if (aspect.equals(ContentModel.ASPECT_TITLED))
				Assert.assertEquals("The signed document looks like the title", ContentModel.ASPECT_TITLED, aspect);
			else {
				Assert.assertEquals("The signed document looks like the doc", VigeWSContentModel.DOC_ASPECT, aspect);
				String idDoc = (String) nodeService.getProperty(result, VigeWSContentModel.ID_DOC);
				Assert.assertEquals("The document has the name of the file", ID_DOC, idDoc);
			}
		}
		Map<String, Object> model = webScriptResponse.getModel();
		Assert.assertEquals("Status ok", STATUS_OK + "", model.get("status").toString());
		logger.debug("end test");
	}
}
